
var Tiro = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(Tiro) {
  Tiro = Tiro || {};


null;var g;g||(g=typeof Tiro !== 'undefined' ? Tiro : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},r;for(r in g)g.hasOwnProperty(r)&&(ca[r]=g[r]);var da="./this.program",w="";"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src);_scriptDir&&(w=_scriptDir);0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="";var ea=g.print||console.log.bind(console),x=g.printErr||console.warn.bind(console);
for(r in ca)ca.hasOwnProperty(r)&&(g[r]=ca[r]);ca=null;g.thisProgram&&(da=g.thisProgram);var y=0,fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime;g.noExitRuntime&&(noExitRuntime=g.noExitRuntime);"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1,la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ra[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=sa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)sa[b>>1]=a.charCodeAt(e),b+=2;sa[b>>1]=0;return b-d}function ua(a){return 2*a.length}function va(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ya,E,A,sa,ra,C,G,za,Aa;
function Ba(){var a=ja.buffer;ya=a;g.HEAP8=E=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=za=new Float32Array(a);g.HEAPF64=Aa=new Float64Array(a)}var H,Ca=[],Da=[],Ea=[],Fa=[];Da.push({Fb:function(){Ga()}});function Ha(){var a=g.preRun.shift();Ca.unshift(a)}var I=0,Ia=null,Ja=null;g.preloadedImages={};g.preloadedAudios={};
function z(a){if(g.onAbort)g.onAbort(a);x(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ka(){var a=J;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var J="tiro.wasm";if(!Ka()){var La=J;J=g.locateFile?g.locateFile(La,w):w+La}
function Ma(){var a=J;try{if(a==J&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}function Na(){return fa||"function"!==typeof fetch?Promise.resolve().then(function(){return Ma()}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ma()})}
function Oa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Fb;"number"===typeof c?void 0===b.vb?H.get(c)():H.get(c)(b.vb):c(void 0===b.vb?null:b.vb)}}}
function K(a){this.Ab=a;this.Ra=a-16;this.Wb=function(b){C[this.Ra+8>>2]=b};this.hb=function(){return C[this.Ra+8>>2]};this.Ub=function(b){C[this.Ra+0>>2]=b};this.Kb=function(){return C[this.Ra+0>>2]};this.Vb=function(){C[this.Ra+4>>2]=0};this.yb=function(b){E[this.Ra+12>>0]=b?1:0};this.Jb=function(){return 0!=E[this.Ra+12>>0]};this.qb=function(b){E[this.Ra+13>>0]=b?1:0};this.Bb=function(){return 0!=E[this.Ra+13>>0]};this.Nb=function(b,c){this.Wb(b);this.Ub(c);this.Vb();this.yb(!1);this.qb(!1)};this.ub=
function(){C[this.Ra+4>>2]+=1};this.Tb=function(){var b=C[this.Ra+4>>2];C[this.Ra+4>>2]=b-1;return 1===b}}
function L(a){this.wb=function(){M(this.Ra);this.Ra=0};this.kb=function(b){C[this.Ra>>2]=b};this.cb=function(){return C[this.Ra>>2]};this.jb=function(b){C[this.Ra+4>>2]=b};this.Ib=function(){return C[this.Ra+4>>2]};this.Lb=function(){if(Pa(this.eb().hb()))return C[this.cb()>>2];var b=this.Ib();return 0!==b?b:this.cb()};this.eb=function(){return new K(this.cb())};void 0===a?(this.Ra=Qa(8),this.jb(0)):this.Ra=a}var N=[],Ra=0;function Sa(a){return M((new K(a)).Ra)}
function Ta(a){if(a.Tb()&&!a.Bb()){var b=a.Kb();b&&H.get(b)(a.Ab);Sa(a.Ab)}}var O=0;function Ua(){var a=N.pop();a||z("no exception to throw");var b=a.eb(),c=a.cb();b.Bb()?a.wb():(N.push(a),b.qb(!0),b.yb(!1),Ra++);O=c;throw c;}function Va(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Wa=void 0;function P(a){for(var b="";A[a];)b+=Wa[A[a++]];return b}var Xa={},Ya={},Za={};
function $a(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ab(a,b){a=$a(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function bb(a){var b=Error,c=ab(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var cb=void 0;function Q(a){throw new cb(a);}var db=void 0;function eb(a){throw new db(a);}
function fb(a,b,c){function d(l){l=c(l);l.length!==a.length&&eb("Mismatched type converter count");for(var n=0;n<a.length;++n)R(a[n],l[n])}a.forEach(function(l){Za[l]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(l,n){Ya.hasOwnProperty(l)?e[n]=Ya[l]:(f.push(l),Xa.hasOwnProperty(l)||(Xa[l]=[]),Xa[l].push(function(){e[n]=Ya[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(Ya.hasOwnProperty(a)){if(c.Mb)return;Q("Cannot register type '"+d+"' twice")}Ya[a]=b;delete Za[a];Xa.hasOwnProperty(a)&&(b=Xa[a],delete Xa[a],b.forEach(function(e){e()}))}function gb(a){return{count:a.count,bb:a.bb,ib:a.ib,Ra:a.Ra,Ta:a.Ta,Va:a.Va,Wa:a.Wa}}
function hb(a){Q(a.Qa.Ta.Sa.name+" instance already deleted")}var ib=!1;function jb(){}function kb(a){--a.count.value;0===a.count.value&&(a.Va?a.Wa.ab(a.Va):a.Ta.Sa.ab(a.Ra))}
function lb(a){if("undefined"===typeof FinalizationGroup)return lb=function(b){return b},a;ib=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Ra?kb(c):console.warn("object already deleted: "+c.Ra)});lb=function(b){ib.register(b,b.Qa,b.Qa);return b};jb=function(b){ib.unregister(b.Qa)};return lb(a)}var mb=void 0,nb=[];function ob(){for(;nb.length;){var a=nb.pop();a.Qa.bb=!1;a["delete"]()}}function S(){}var pb={};
function qb(a,b,c){if(void 0===a[b].Ya){var d=a[b];a[b]=function(){a[b].Ya.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ya+")!");return a[b].Ya[arguments.length].apply(this,arguments)};a[b].Ya=[];a[b].Ya[d.nb]=d}}
function rb(a,b){g.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),qb(g,a,a),g.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].Ya[void 0]=b):g[a]=b}function sb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.fb=c;this.ab=d;this.Xa=e;this.Gb=f;this.mb=k;this.Eb=l;this.Pb=[]}
function tb(a,b,c){for(;b!==c;)b.mb||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.mb(a),b=b.Xa;return a}function ub(a,b){if(null===b)return this.xb&&Q("null is not a valid "+this.name),0;b.Qa||Q('Cannot pass "'+vb(b)+'" as a '+this.name);b.Qa.Ra||Q("Cannot pass deleted object as a pointer of type "+this.name);return tb(b.Qa.Ra,b.Qa.Ta.Sa,this.Sa)}
function wb(a,b){if(null===b){this.xb&&Q("null is not a valid "+this.name);if(this.pb){var c=this.Qb();null!==a&&a.push(this.ab,c);return c}return 0}b.Qa||Q('Cannot pass "'+vb(b)+'" as a '+this.name);b.Qa.Ra||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.ob&&b.Qa.Ta.ob&&Q("Cannot convert argument of type "+(b.Qa.Wa?b.Qa.Wa.name:b.Qa.Ta.name)+" to parameter type "+this.name);c=tb(b.Qa.Ra,b.Qa.Ta.Sa,this.Sa);if(this.pb)switch(void 0===b.Qa.Va&&Q("Passing raw pointer to smart pointer is illegal"),
this.Xb){case 0:b.Qa.Wa===this?c=b.Qa.Va:Q("Cannot convert argument of type "+(b.Qa.Wa?b.Qa.Wa.name:b.Qa.Ta.name)+" to parameter type "+this.name);break;case 1:c=b.Qa.Va;break;case 2:if(b.Qa.Wa===this)c=b.Qa.Va;else{var d=b.clone();c=this.Rb(c,xb(function(){d["delete"]()}));null!==a&&a.push(this.ab,c)}break;default:Q("Unsupporting sharing policy")}return c}
function yb(a,b){if(null===b)return this.xb&&Q("null is not a valid "+this.name),0;b.Qa||Q('Cannot pass "'+vb(b)+'" as a '+this.name);b.Qa.Ra||Q("Cannot pass deleted object as a pointer of type "+this.name);b.Qa.Ta.ob&&Q("Cannot convert argument of type "+b.Qa.Ta.name+" to parameter type "+this.name);return tb(b.Qa.Ra,b.Qa.Ta.Sa,this.Sa)}function zb(a){return this.fromWireType(G[a>>2])}function Ab(a,b,c){if(b===c)return a;if(void 0===c.Xa)return null;a=Ab(a,b,c.Xa);return null===a?null:c.Eb(a)}
var Bb={};function Cb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.Xa;)b=a.mb(b),a=a.Xa;return Bb[b]}function Db(a,b){b.Ta&&b.Ra||eb("makeClassHandle requires ptr and ptrType");!!b.Wa!==!!b.Va&&eb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return lb(Object.create(a,{Qa:{value:b}}))}
function T(a,b,c,d){this.name=a;this.Sa=b;this.xb=c;this.ob=d;this.pb=!1;this.ab=this.Rb=this.Qb=this.Cb=this.Xb=this.Ob=void 0;void 0!==b.Xa?this.toWireType=wb:(this.toWireType=d?ub:yb,this.Za=null)}function Eb(a,b){g.hasOwnProperty(a)||eb("Replacing nonexistant public symbol");g[a]=b;g[a].nb=void 0}
function Fb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=H.get(b).apply(null,c);return d}}function Gb(a,b){a=P(a);var c=-1!=a.indexOf("j")?Fb(a,b):H.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Hb=void 0;function Ib(a){a=Lb(a);var b=P(a);M(a);return b}
function Mb(a,b){function c(f){e[f]||Ya[f]||(Za[f]?Za[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Hb(a+": "+d.map(Ib).join([", "]));}function Nb(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}function Ob(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Pb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ab(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Qb=[],U=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function xb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qb.length?Qb.pop():U.length;U[b]={Sb:1,value:a};return b}}function vb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Rb(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Sb(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return A[d]};case 1:return c?function(d){return sa[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Tb;Tb=function(){return performance.now()};var Ub={};
function Vb(){if(!Wb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Ub)a[b]=Ub[b];var c=[];for(b in a)c.push(b+"="+a[b]);Wb=c}return Wb}var Wb,Xb=[null,[],[]];function Yb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Zb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var $b=[31,29,31,30,31,30,31,31,30,31,30,31],ac=[31,28,31,30,31,30,31,31,30,31,30,31];function bc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Yb(a.getFullYear())?$b:ac)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function cc(a,b,c,d){function e(h,p,u){for(h="number"===typeof h?h.toString():h||"";h.length<p;)h=u[0]+h;return h}function f(h,p){return e(h,p,"0")}function k(h,p){function u(D){return 0>D?-1:0<D?1:0}var t;0===(t=u(h.getFullYear()-p.getFullYear()))&&0===(t=u(h.getMonth()-p.getMonth()))&&(t=u(h.getDate()-p.getDate()));return t}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=bc(new Date(h.Ua+1900,0,1),h.tb);var p=new Date(h.getFullYear()+1,0,4),u=l(new Date(h.getFullYear(),0,4));p=l(p);return 0>=k(u,h)?0>=k(p,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=C[d+40>>2];d={$b:C[d>>2],Zb:C[d+4>>2],rb:C[d+8>>2],lb:C[d+12>>2],gb:C[d+16>>2],Ua:C[d+20>>2],sb:C[d+24>>2],tb:C[d+28>>2],cc:C[d+32>>2],Yb:C[d+
36>>2],ac:m?m?ma(A,m,void 0):"":""};c=c?ma(A,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return B[h.sb].substring(0,3)},"%A":function(h){return B[h.sb]},"%b":function(h){return v[h.gb].substring(0,3)},"%B":function(h){return v[h.gb]},"%C":function(h){return f((h.Ua+1900)/100|0,2)},"%d":function(h){return f(h.lb,2)},"%e":function(h){return e(h.lb,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return f(h.rb,
2)},"%I":function(h){h=h.rb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.lb+Zb(Yb(h.Ua+1900)?$b:ac,h.gb-1),3)},"%m":function(h){return f(h.gb+1,2)},"%M":function(h){return f(h.Zb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.rb&&12>h.rb?"AM":"PM"},"%S":function(h){return f(h.$b,2)},"%t":function(){return"\t"},"%u":function(h){return h.sb||7},"%U":function(h){var p=new Date(h.Ua+1900,0,1),u=0===p.getDay()?p:bc(p,7-p.getDay());h=new Date(h.Ua+1900,h.gb,h.lb);return 0>
k(u,h)?f(Math.ceil((31-u.getDate()+(Zb(Yb(h.getFullYear())?$b:ac,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(u,p)?"01":"00"},"%V":function(h){var p=new Date(h.Ua+1901,0,4),u=l(new Date(h.Ua+1900,0,4));p=l(p);var t=bc(new Date(h.Ua+1900,0,1),h.tb);return 0>k(t,u)?"53":0>=k(p,t)?"01":f(Math.ceil((u.getFullYear()<h.Ua+1900?h.tb+32-u.getDate():h.tb+1-u.getDate())/7),2)},"%w":function(h){return h.sb},"%W":function(h){var p=new Date(h.Ua,0,1),u=1===p.getDay()?p:bc(p,0===p.getDay()?1:7-p.getDay()+1);h=
new Date(h.Ua+1900,h.gb,h.lb);return 0>k(u,h)?f(Math.ceil((31-u.getDate()+(Zb(Yb(h.getFullYear())?$b:ac,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(u,p)?"01":"00"},"%y":function(h){return(h.Ua+1900).toString().substring(2)},"%Y":function(h){return h.Ua+1900},"%z":function(h){h=h.Yb;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.ac},"%%":function(){return"%"}};for(q in m)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));q=
dc(c);if(q.length>b)return 0;E.set(q,a);return q.length-1}for(var ec=Array(256),fc=0;256>fc;++fc)ec[fc]=String.fromCharCode(fc);Wa=ec;cb=g.BindingError=bb("BindingError");db=g.InternalError=bb("InternalError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.Qa.Ta.Sa,c=this.Qa.Ra,d=a.Qa.Ta.Sa;for(a=a.Qa.Ra;b.Xa;)c=b.mb(c),b=b.Xa;for(;d.Xa;)a=d.mb(a),d=d.Xa;return b===d&&c===a};
S.prototype.clone=function(){this.Qa.Ra||hb(this);if(this.Qa.ib)return this.Qa.count.value+=1,this;var a=lb(Object.create(Object.getPrototypeOf(this),{Qa:{value:gb(this.Qa)}}));a.Qa.count.value+=1;a.Qa.bb=!1;return a};S.prototype["delete"]=function(){this.Qa.Ra||hb(this);this.Qa.bb&&!this.Qa.ib&&Q("Object already scheduled for deletion");jb(this);kb(this.Qa);this.Qa.ib||(this.Qa.Va=void 0,this.Qa.Ra=void 0)};S.prototype.isDeleted=function(){return!this.Qa.Ra};
S.prototype.deleteLater=function(){this.Qa.Ra||hb(this);this.Qa.bb&&!this.Qa.ib&&Q("Object already scheduled for deletion");nb.push(this);1===nb.length&&mb&&mb(ob);this.Qa.bb=!0;return this};T.prototype.Hb=function(a){this.Cb&&(a=this.Cb(a));return a};T.prototype.zb=function(a){this.ab&&this.ab(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=zb;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.pb?Db(this.Sa.fb,{Ta:this.Ob,Ra:c,Wa:this,Va:a}):Db(this.Sa.fb,{Ta:this,Ra:a})}var c=this.Hb(a);if(!c)return this.zb(a),null;var d=Cb(this.Sa,c);if(void 0!==d){if(0===d.Qa.count.value)return d.Qa.Ra=c,d.Qa.Va=a,d.clone();d=d.clone();this.zb(a);return d}d=this.Sa.Gb(c);d=pb[d];if(!d)return b.call(this);d=this.ob?d.Db:d.pointerType;var e=Ab(c,this.Sa,d.Sa);return null===e?b.call(this):this.pb?Db(d.Sa.fb,{Ta:d,Ra:e,Wa:this,Va:a}):Db(d.Sa.fb,
{Ta:d,Ra:e})};g.getInheritedInstanceCount=function(){return Object.keys(Bb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Bb)Bb.hasOwnProperty(b)&&a.push(Bb[b]);return a};g.flushPendingDeletes=ob;g.setDelayFunction=function(a){mb=a;nb.length&&mb&&mb(ob)};Hb=g.UnboundTypeError=bb("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<U.length;++b)void 0!==U[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<U.length;++a)if(void 0!==U[a])return U[a];return null};
function dc(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}
var Pc={m:function(a){return Qa(a+16)+16},p:function(a){a=new L(a);var b=a.eb();b.Jb()||(b.yb(!0),Ra--);b.qb(!1);N.push(a);b.ub();return a.Lb()},da:function(){if(!N.length)return 0;var a=N[N.length-1];a.eb().ub();return a.cb()},N:function(a){a&&Ta(new K(a))},s:function(){V(0);var a=N.pop();Ta(a.eb());a.wb();O=0},b:function(){var a=O;if(!a)return y=0;var b=(new K(a)).hb(),c=new L;c.kb(a);if(!b)return y=0,c.Ra|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=
d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.jb(b),y=l|0,c.Ra|0}Z(e);y=b|0;return c.Ra|0},h:function(){var a=O;if(!a)return y=0;var b=(new K(a)).hb(),c=new L;c.kb(a);if(!b)return y=0,c.Ra|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.jb(b),y=l|0,c.Ra|0}Z(e);y=b|0;return c.Ra|0},v:function(){var a=O;if(!a)return y=0;var b=(new K(a)).hb(),c=new L;c.kb(a);if(!b)return y=
0,c.Ra|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.jb(b),y=l|0,c.Ra|0}Z(e);y=b|0;return c.Ra|0},na:function(){var a=O;if(!a)return y=0;var b=(new K(a)).hb(),c=new L;c.kb(a);if(!b)return y=0,c.Ra|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=gc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(hc(l,b,f))return b=C[f>>2],a!==b&&c.jb(b),y=l|
0,c.Ra|0}Z(e);y=b|0;return c.Ra|0},q:Sa,M:function(a){a&&(new K(a)).ub()},Q:Ua,ca:function(a){if(a){var b=new L;b.kb(a);a=b.eb();N.push(b);a.qb(!0);Ua()}},r:function(a,b,c){(new K(a)).Nb(b,c);O=a;Ra++;throw a;},l:function(){return Ra},f:function(a){a=new L(a);var b=a.cb();O||(O=b);a.wb();throw b;},ka:function(a,b,c,d,e){var f=Va(c);b=P(b);R(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=E;else if(2===
c)l=sa;else if(4===c)l=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},Za:null})},pa:function(a,b,c,d,e,f,k,l,n,m,q,B,v){q=P(q);f=Gb(e,f);l&&(l=Gb(k,l));m&&(m=Gb(n,m));v=Gb(B,v);var h=$a(q);rb(h,function(){Mb("Cannot construct "+q+" due to unbound types",[d])});fb([a,b,c],d?[d]:[],function(p){p=p[0];if(d){var u=p.Sa;var t=u.fb}else t=S.prototype;p=ab(h,function(){if(Object.getPrototypeOf(this)!==D)throw new cb("Use 'new' to construct "+q);if(void 0===
F.$a)throw new cb(q+" has no accessible constructor");var W=F.$a[arguments.length];if(void 0===W)throw new cb("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(F.$a).toString()+") parameters instead!");return W.apply(this,arguments)});var D=Object.create(t,{constructor:{value:p}});p.prototype=D;var F=new sb(q,p,D,v,u,f,l,m);u=new T(q,F,!0,!1);t=new T(q+"*",F,!1,!1);var ha=new T(q+" const*",F,!1,!0);pb[a]={pointerType:t,Db:ha};Eb(h,p);
return[u,t,ha]})},oa:function(a,b,c,d,e,f){0<b||z("Assertion failed: undefined");var k=Nb(b,c);e=Gb(d,e);var l=[f],n=[];fb([],[a],function(m){m=m[0];var q="constructor "+m.name;void 0===m.Sa.$a&&(m.Sa.$a=[]);if(void 0!==m.Sa.$a[b-1])throw new cb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.Sa.$a[b-1]=function(){Mb("Cannot construct "+
m.name+" due to unbound types",k)};fb([],k,function(B){m.Sa.$a[b-1]=function(){arguments.length!==b-1&&Q(q+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var v=1;v<b;++v)l[v]=B[v].toWireType(n,arguments[v-1]);v=e.apply(null,l);Ob(n);return B[0].fromWireType(v)};return[]});return[]})},L:function(a,b,c,d,e,f,k,l){var n=Nb(c,d);b=P(b);f=Gb(e,f);fb([],[a],function(m){function q(){Mb("Cannot call "+B+" due to unbound types",n)}m=m[0];var B=m.name+"."+b;l&&m.Sa.Pb.push(b);
var v=m.Sa.fb,h=v[b];void 0===h||void 0===h.Ya&&h.className!==m.name&&h.nb===c-2?(q.nb=c-2,q.className=m.name,v[b]=q):(qb(v,b,B),v[b].Ya[c-2]=q);fb([],n,function(p){var u=B,t=m,D=f,F=p.length;2>F&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var ha=null!==p[1]&&null!==t,W=!1;for(t=1;t<p.length;++t)if(null!==p[t]&&void 0===p[t].Za){W=!0;break}var Jb="void"!==p[0].name,X="",ia="";for(t=0;t<F-2;++t)X+=(0!==t?", ":"")+"arg"+t,ia+=(0!==t?", ":"")+"arg"+t+"Wired";
u="return function "+$a(u)+"("+X+") {\nif (arguments.length !== "+(F-2)+") {\nthrowBindingError('function "+u+" called with ' + arguments.length + ' arguments, expected "+(F-2)+" args!');\n}\n";W&&(u+="var destructors = [];\n");var Kb=W?"destructors":"null";X="throwBindingError invoker fn runDestructors retType classParam".split(" ");D=[Q,D,k,Ob,p[0],p[1]];ha&&(u+="var thisWired = classParam.toWireType("+Kb+", this);\n");for(t=0;t<F-2;++t)u+="var arg"+t+"Wired = argType"+t+".toWireType("+Kb+", arg"+
t+"); // "+p[t+2].name+"\n",X.push("argType"+t),D.push(p[t+2]);ha&&(ia="thisWired"+(0<ia.length?", ":"")+ia);u+=(Jb?"var rv = ":"")+"invoker(fn"+(0<ia.length?", ":"")+ia+");\n";if(W)u+="runDestructors(destructors);\n";else for(t=ha?1:2;t<p.length;++t)F=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==p[t].Za&&(u+=F+"_dtor("+F+"); // "+p[t].name+"\n",X.push(F+"_dtor"),D.push(p[t].Za));Jb&&(u+="var ret = retType.fromWireType(rv);\nreturn ret;\n");X.push(u+"}\n");p=Pb(X).apply(null,D);void 0===v[b].Ya?(p.nb=
c-2,v[b]=p):v[b].Ya[c-2]=p;return[]});return[]})},ja:function(a,b){b=P(b);R(a,{name:b,fromWireType:function(c){var d=U[c].value;4<c&&0===--U[c].Sb&&(U[c]=void 0,Qb.push(c));return d},toWireType:function(c,d){return xb(d)},argPackAdvance:8,readValueFromPointer:zb,Za:null})},S:function(a,b,c){c=Va(c);b=P(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+vb(e)+'" to '+this.name);return e},argPackAdvance:8,
readValueFromPointer:Rb(b,c),Za:null})},C:function(a,b,c,d,e){function f(m){return m}b=P(b);-1===e&&(e=4294967295);var k=Va(c);if(0===d){var l=32-8*c;f=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");R(a,{name:b,fromWireType:f,toWireType:function(m,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+vb(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+vb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+
d+", "+e+"]!");return n?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Sb(b,k,0!==d),Za:null})},B:function(a,b,c){function d(f){f>>=2;var k=G;return new e(ya,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Mb:!0})},T:function(a,b){b=P(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var l=d+
4+k;if(k==e||0==A[l]){f=f?ma(A,f,l-f):"";if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(A[d+4+k]);n=n.join("")}M(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var k=(c&&f?function(){return oa(e)}:function(){return e.length})(),l=Qa(4+
k+1);G[l>>2]=k;if(c&&f)na(e,A,l+4,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);255<n&&(M(l),Q("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=n}else for(f=0;f<k;++f)A[l+4+f]=e[f];null!==d&&d.push(M,l);return l},argPackAdvance:8,readValueFromPointer:zb,Za:function(d){M(d)}})},J:function(a,b,c){c=P(c);if(2===b){var d=qa;var e=ta;var f=ua;var k=function(){return ra};var l=1}else 4===b&&(d=va,e=wa,f=xa,k=function(){return G},l=2);R(a,{name:c,fromWireType:function(n){for(var m=
G[n>>2],q=k(),B,v=n+4,h=0;h<=m;++h){var p=n+4+h*b;if(h==m||0==q[p>>l])v=d(v,p-v),void 0===B?B=v:(B+=String.fromCharCode(0),B+=v),v=p+b}M(n);return B},toWireType:function(n,m){"string"!==typeof m&&Q("Cannot pass non-string to C++ string type "+c);var q=f(m),B=Qa(4+q+b);G[B>>2]=q>>l;e(m,B+4,q+b);null!==n&&n.push(M,B);return B},argPackAdvance:8,readValueFromPointer:zb,Za:function(n){M(n)}})},la:function(a,b){b=P(b);R(a,{bc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
ia:function(){z()},ba:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Tb();else return C[ic()>>2]=28,-1;C[b>>2]=a/1E3|0;C[b+4>>2]=a%1E3*1E6|0;return 0},$:function(a,b,c){A.copyWithin(a,b,b+c)},aa:function(a){a>>>=0;var b=A.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-ya.byteLength+65535>>>16);Ba();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
ga:function(a,b){var c=0;Vb().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)E[e++>>0]=d.charCodeAt(f);E[e>>0]=0;c+=d.length+1});return 0},ha:function(a,b){var c=Vb();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},R:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var k=C[b+8*f>>2],l=C[b+(8*f+4)>>2],n=0;n<l;n++){var m=A[k+n],q=Xb[a];0===m||10===m?((1===a?ea:x)(ma(q,0)),q.length=0):q.push(m)}e+=l}C[d>>2]=e;return 0},a:function(){return y|0},
O:jc,P:kc,t:lc,x:mc,d:nc,I:oc,ma:pc,c:qc,k:rc,o:sc,u:tc,D:uc,K:vc,H:wc,_:xc,W:yc,Z:zc,Y:Ac,X:Bc,U:Cc,V:Dc,n:Ec,i:Fc,e:Gc,ea:Hc,g:Ic,j:Jc,w:Kc,y:Lc,A:Mc,E:Nc,G:Oc,z:function(a){return a},F:function(a){y=a|0},fa:function(a,b,c,d){return cc(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ja=g.asm.qa;Ba();H=g.asm.va;I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja&&(e=Ja,Ja=null,e()))}function b(e){a(e.instance)}function c(e){return Na().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){x("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:Pc};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!==typeof WebAssembly.instantiateStreaming||Ka()||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){x("wasm streaming compile failed: "+f);x("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var Ga=g.___wasm_call_ctors=function(){return(Ga=g.___wasm_call_ctors=g.asm.ra).apply(null,arguments)},ic=g.___errno_location=function(){return(ic=g.___errno_location=g.asm.sa).apply(null,arguments)},M=g._free=function(){return(M=g._free=g.asm.ta).apply(null,arguments)},Qa=g._malloc=function(){return(Qa=g._malloc=g.asm.ua).apply(null,arguments)},Lb=g.___getTypeName=function(){return(Lb=g.___getTypeName=g.asm.wa).apply(null,arguments)};
g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.xa).apply(null,arguments)};
var Y=g.stackSave=function(){return(Y=g.stackSave=g.asm.ya).apply(null,arguments)},Z=g.stackRestore=function(){return(Z=g.stackRestore=g.asm.za).apply(null,arguments)},gc=g.stackAlloc=function(){return(gc=g.stackAlloc=g.asm.Aa).apply(null,arguments)},V=g._setThrew=function(){return(V=g._setThrew=g.asm.Ba).apply(null,arguments)},hc=g.___cxa_can_catch=function(){return(hc=g.___cxa_can_catch=g.asm.Ca).apply(null,arguments)},Pa=g.___cxa_is_pointer_type=function(){return(Pa=g.___cxa_is_pointer_type=g.asm.Da).apply(null,
arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ea).apply(null,arguments)};
var Qc=g.dynCall_iij=function(){return(Qc=g.dynCall_iij=g.asm.Fa).apply(null,arguments)},Rc=g.dynCall_ijj=function(){return(Rc=g.dynCall_ijj=g.asm.Ga).apply(null,arguments)},Sc=g.dynCall_ijjiii=function(){return(Sc=g.dynCall_ijjiii=g.asm.Ha).apply(null,arguments)},Tc=g.dynCall_ji=function(){return(Tc=g.dynCall_ji=g.asm.Ia).apply(null,arguments)},Uc=g.dynCall_iijj=function(){return(Uc=g.dynCall_iijj=g.asm.Ja).apply(null,arguments)};
g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ka).apply(null,arguments)};var Vc=g.dynCall_jiiii=function(){return(Vc=g.dynCall_jiiii=g.asm.La).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ma).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Na).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Oa).apply(null,arguments)};
var Wc=g.dynCall_jii=function(){return(Wc=g.dynCall_jii=g.asm.Pa).apply(null,arguments)};function nc(a,b){var c=Y();try{return H.get(a)(b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function Fc(a,b){var c=Y();try{H.get(a)(b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function qc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}
function Lc(a,b,c,d,e,f,k){var l=Y();try{H.get(a)(b,c,d,e,f,k)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;V(1,0)}}function Jc(a,b,c,d,e){var f=Y();try{H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function Gc(a,b,c){var d=Y();try{H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function Ic(a,b,c,d){var e=Y();try{H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}
function Ec(a){var b=Y();try{H.get(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;V(1,0)}}function rc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function tc(a,b,c,d,e,f){var k=Y();try{return H.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function lc(a){var b=Y();try{return H.get(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;V(1,0)}}
function Kc(a,b,c,d,e,f){var k=Y();try{H.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function sc(a,b,c,d,e){var f=Y();try{return H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function uc(a,b,c,d,e,f,k){var l=Y();try{return H.get(a)(b,c,d,e,f,k)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;V(1,0)}}function oc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}
function mc(a,b,c,d,e){var f=Y();try{return H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function vc(a,b,c,d,e,f,k,l){var n=Y();try{return H.get(a)(b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function pc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function kc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}
function jc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function Mc(a,b,c,d,e,f,k,l){var n=Y();try{H.get(a)(b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function wc(a,b,c,d,e,f,k,l,n,m,q,B){var v=Y();try{return H.get(a)(b,c,d,e,f,k,l,n,m,q,B)}catch(h){Z(v);if(h!==h+0&&"longjmp"!==h)throw h;V(1,0)}}
function Nc(a,b,c,d,e,f,k,l,n,m,q){var B=Y();try{H.get(a)(b,c,d,e,f,k,l,n,m,q)}catch(v){Z(B);if(v!==v+0&&"longjmp"!==v)throw v;V(1,0)}}function Oc(a,b,c,d,e,f,k,l,n,m,q,B,v,h,p,u){var t=Y();try{H.get(a)(b,c,d,e,f,k,l,n,m,q,B,v,h,p,u)}catch(D){Z(t);if(D!==D+0&&"longjmp"!==D)throw D;V(1,0)}}function Hc(a,b,c,d){var e=Y();try{H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}
function xc(a,b,c,d){var e=Y();try{return Qc(a,b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function zc(a,b,c,d,e){var f=Y();try{return Rc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function Ac(a,b,c,d,e,f,k,l){var n=Y();try{return Sc(a,b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function Bc(a,b){var c=Y();try{return Tc(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}
function yc(a,b,c,d,e,f){var k=Y();try{return Uc(a,b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function Dc(a,b,c,d,e){var f=Y();try{return Vc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function Cc(a,b,c){var d=Y();try{return Wc(a,b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}var Xc;Ja=function Yc(){Xc||Zc();Xc||(Ja=Yc)};
function Zc(){function a(){if(!Xc&&(Xc=!0,g.calledRun=!0,!ka)){Oa(Da);Oa(Ea);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Fa.unshift(b)}Oa(Fa)}}if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ha();Oa(Ca);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
g.run=Zc;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();noExitRuntime=!0;Zc();


  return Tiro.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Tiro;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Tiro; });
else if (typeof exports === 'object')
  exports["Tiro"] = Tiro;
