
var Tiro = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(Tiro) {
  Tiro = Tiro || {};


null;var g;g||(g=typeof Tiro !== 'undefined' ? Tiro : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},r;for(r in g)g.hasOwnProperty(r)&&(ca[r]=g[r]);var da="./this.program",w="";"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src);_scriptDir&&(w=_scriptDir);0!==w.indexOf("blob:")?w=w.substr(0,w.lastIndexOf("/")+1):w="";var ea=g.print||console.log.bind(console),x=g.printErr||console.warn.bind(console);
for(r in ca)ca.hasOwnProperty(r)&&(g[r]=ca[r]);ca=null;g.thisProgram&&(da=g.thisProgram);var y=0,fa;g.wasmBinary&&(fa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&z("no native wasm support detected");var ja,ka=!1,la="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ma(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&la)return la.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function na(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ra[c];)++c;c<<=1;if(32<c-a&&pa)return pa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=sa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)sa[b>>1]=a.charCodeAt(e),b+=2;sa[b>>1]=0;return b-d}function ua(a){return 2*a.length}function va(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}C[b>>2]=f;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ya,E,A,sa,ra,C,G,za,Aa;
function Ba(){var a=ja.buffer;ya=a;g.HEAP8=E=new Int8Array(a);g.HEAP16=sa=new Int16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=ra=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=za=new Float32Array(a);g.HEAPF64=Aa=new Float64Array(a)}var H,Ca=[],Da=[],Ea=[];function Fa(){var a=g.preRun.shift();Ca.unshift(a)}var I=0,Ga=null,Ha=null;g.preloadedImages={};g.preloadedAudios={};
function z(a){if(g.onAbort)g.onAbort(a);x(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ia(){return J.startsWith("data:application/octet-stream;base64,")}var J="tiro.wasm";if(!Ia()){var Ja=J;J=g.locateFile?g.locateFile(Ja,w):w+Ja}function Ka(){var a=J;try{if(a==J&&fa)return new Uint8Array(fa);throw"both async and sync fetching of the wasm failed";}catch(b){z(b)}}
function La(){return fa||"function"!==typeof fetch?Promise.resolve().then(function(){return Ka()}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ka()})}function Ma(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Ub;"number"===typeof c?void 0===b.ob?H.get(c)():H.get(c)(b.ob):c(void 0===b.ob?null:b.ob)}}}
function K(a){this.tb=a;this.Ka=a-16;this.Ob=function(b){C[this.Ka+8>>2]=b};this.$a=function(){return C[this.Ka+8>>2]};this.Mb=function(b){C[this.Ka+0>>2]=b};this.Cb=function(){return C[this.Ka+0>>2]};this.Nb=function(){C[this.Ka+4>>2]=0};this.rb=function(b){E[this.Ka+12>>0]=b?1:0};this.Bb=function(){return 0!=E[this.Ka+12>>0]};this.jb=function(b){E[this.Ka+13>>0]=b?1:0};this.ub=function(){return 0!=E[this.Ka+13>>0]};this.Fb=function(b,c){this.Ob(b);this.Mb(c);this.Nb();this.rb(!1);this.jb(!1)};this.nb=
function(){C[this.Ka+4>>2]=C[this.Ka+4>>2]+1};this.Lb=function(){var b=C[this.Ka+4>>2];C[this.Ka+4>>2]=b-1;return 1===b}}
function L(a){this.pb=function(){M(this.Ka);this.Ka=0};this.cb=function(b){C[this.Ka>>2]=b};this.Wa=function(){return C[this.Ka>>2]};this.bb=function(b){C[this.Ka+4>>2]=b};this.Ab=function(){return C[this.Ka+4>>2]};this.Db=function(){if(Na(this.Xa().$a()))return C[this.Wa()>>2];var b=this.Ab();return 0!==b?b:this.Wa()};this.Xa=function(){return new K(this.Wa())};void 0===a?(this.Ka=Oa(8),this.bb(0)):this.Ka=a}var N=[],Pa=0;function Qa(a){return M((new K(a)).Ka)}
function Ra(a){if(a.Lb()&&!a.ub()){var b=a.Cb();b&&H.get(b)(a.tb);Qa(a.tb)}}var O=0;function Sa(){var a=N.pop();a||z("no exception to throw");var b=a.Xa(),c=a.Wa();b.ub()?a.pb():(N.push(a),b.jb(!0),b.rb(!1),Pa++);O=c;throw c;}function Ta(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ua=void 0;function P(a){for(var b="";A[a];)b+=Ua[A[a++]];return b}var Va={},Wa={},Xa={};
function Ya(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Za(a,b){a=Ya(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function $a(a){var b=Error,c=Za(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var ab=void 0;function Q(a){throw new ab(a);}var bb=void 0;function cb(a){throw new bb(a);}
function db(a,b,c){function d(l){l=c(l);l.length!==a.length&&cb("Mismatched type converter count");for(var n=0;n<a.length;++n)R(a[n],l[n])}a.forEach(function(l){Xa[l]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(l,n){Wa.hasOwnProperty(l)?e[n]=Wa[l]:(f.push(l),Va.hasOwnProperty(l)||(Va[l]=[]),Va[l].push(function(){e[n]=Wa[l];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(Wa.hasOwnProperty(a)){if(c.Eb)return;Q("Cannot register type '"+d+"' twice")}Wa[a]=b;delete Xa[a];Va.hasOwnProperty(a)&&(b=Va[a],delete Va[a],b.forEach(function(e){e()}))}function eb(a){Q(a.Ja.Ma.La.name+" instance already deleted")}var fb=!1;function gb(){}
function hb(a){--a.count.value;0===a.count.value&&(a.Oa?a.Pa.Ua(a.Oa):a.Ma.La.Ua(a.Ka))}function ib(a){if("undefined"===typeof FinalizationGroup)return ib=function(b){return b},a;fb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Ka?hb(c):console.warn("object already deleted: "+c.Ka)});ib=function(b){fb.register(b,b.Ja,b.Ja);return b};gb=function(b){fb.unregister(b.Ja)};return ib(a)}var jb=void 0,kb=[];
function lb(){for(;kb.length;){var a=kb.pop();a.Ja.Va=!1;a["delete"]()}}function S(){}var mb={};function nb(a,b,c){if(void 0===a[b].Ra){var d=a[b];a[b]=function(){a[b].Ra.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Ra+")!");return a[b].Ra[arguments.length].apply(this,arguments)};a[b].Ra=[];a[b].Ra[d.gb]=d}}
function ob(a,b){g.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),nb(g,a,a),g.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].Ra[void 0]=b):g[a]=b}function pb(a,b,c,d,e,f,k,l){this.name=a;this.constructor=b;this.Ya=c;this.Ua=d;this.Qa=e;this.yb=f;this.fb=k;this.xb=l;this.Hb=[]}
function qb(a,b,c){for(;b!==c;)b.fb||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.fb(a),b=b.Qa;return a}function rb(a,b){if(null===b)return this.qb&&Q("null is not a valid "+this.name),0;b.Ja||Q('Cannot pass "'+sb(b)+'" as a '+this.name);b.Ja.Ka||Q("Cannot pass deleted object as a pointer of type "+this.name);return qb(b.Ja.Ka,b.Ja.Ma.La,this.La)}
function tb(a,b){if(null===b){this.qb&&Q("null is not a valid "+this.name);if(this.ib){var c=this.Ib();null!==a&&a.push(this.Ua,c);return c}return 0}b.Ja||Q('Cannot pass "'+sb(b)+'" as a '+this.name);b.Ja.Ka||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.hb&&b.Ja.Ma.hb&&Q("Cannot convert argument of type "+(b.Ja.Pa?b.Ja.Pa.name:b.Ja.Ma.name)+" to parameter type "+this.name);c=qb(b.Ja.Ka,b.Ja.Ma.La,this.La);if(this.ib)switch(void 0===b.Ja.Oa&&Q("Passing raw pointer to smart pointer is illegal"),
this.Pb){case 0:b.Ja.Pa===this?c=b.Ja.Oa:Q("Cannot convert argument of type "+(b.Ja.Pa?b.Ja.Pa.name:b.Ja.Ma.name)+" to parameter type "+this.name);break;case 1:c=b.Ja.Oa;break;case 2:if(b.Ja.Pa===this)c=b.Ja.Oa;else{var d=b.clone();c=this.Jb(c,ub(function(){d["delete"]()}));null!==a&&a.push(this.Ua,c)}break;default:Q("Unsupporting sharing policy")}return c}
function vb(a,b){if(null===b)return this.qb&&Q("null is not a valid "+this.name),0;b.Ja||Q('Cannot pass "'+sb(b)+'" as a '+this.name);b.Ja.Ka||Q("Cannot pass deleted object as a pointer of type "+this.name);b.Ja.Ma.hb&&Q("Cannot convert argument of type "+b.Ja.Ma.name+" to parameter type "+this.name);return qb(b.Ja.Ka,b.Ja.Ma.La,this.La)}function wb(a){return this.fromWireType(G[a>>2])}function xb(a,b,c){if(b===c)return a;if(void 0===c.Qa)return null;a=xb(a,b,c.Qa);return null===a?null:c.xb(a)}
var yb={};function zb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.Qa;)b=a.fb(b),a=a.Qa;return yb[b]}function Ab(a,b){b.Ma&&b.Ka||cb("makeClassHandle requires ptr and ptrType");!!b.Pa!==!!b.Oa&&cb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ib(Object.create(a,{Ja:{value:b}}))}
function T(a,b,c,d){this.name=a;this.La=b;this.qb=c;this.hb=d;this.ib=!1;this.Ua=this.Jb=this.Ib=this.vb=this.Pb=this.Gb=void 0;void 0!==b.Qa?this.toWireType=tb:(this.toWireType=d?rb:vb,this.Sa=null)}function Bb(a,b){g.hasOwnProperty(a)||cb("Replacing nonexistant public symbol");g[a]=b;g[a].gb=void 0}
function Cb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=H.get(b).apply(null,c);return d}}function Db(a,b){a=P(a);var c=a.includes("j")?Cb(a,b):H.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Eb=void 0;function Fb(a){a=Gb(a);var b=P(a);M(a);return b}
function Hb(a,b){function c(f){e[f]||Wa[f]||(Xa[f]?Xa[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Eb(a+": "+d.map(Fb).join([", "]));}function Kb(a,b){for(var c=[],d=0;d<a;d++)c.push(C[(b>>2)+d]);return c}function Lb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Mb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Za(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var Nb=[],U=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function ub(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Nb.length?Nb.pop():U.length;U[b]={Kb:1,value:a};return b}}function sb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Ob(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Pb(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return A[d]};case 1:return c?function(d){return sa[d>>1]}:function(d){return ra[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Qb;Qb=function(){return performance.now()};var Rb={};
function Sb(){if(!Tb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Rb)a[b]=Rb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Tb=c}return Tb}var Tb,Ub=[null,[],[]];function Vb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Wb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Xb=[31,29,31,30,31,30,31,31,30,31,30,31],Yb=[31,28,31,30,31,30,31,31,30,31,30,31];function Zb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Vb(a.getFullYear())?Xb:Yb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function $b(a,b,c,d){function e(h,p,u){for(h="number"===typeof h?h.toString():h||"";h.length<p;)h=u[0]+h;return h}function f(h,p){return e(h,p,"0")}function k(h,p){function u(D){return 0>D?-1:0<D?1:0}var t;0===(t=u(h.getFullYear()-p.getFullYear()))&&0===(t=u(h.getMonth()-p.getMonth()))&&(t=u(h.getDate()-p.getDate()));return t}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=Zb(new Date(h.Na+1900,0,1),h.mb);var p=new Date(h.getFullYear()+1,0,4),u=l(new Date(h.getFullYear(),0,4));p=l(p);return 0>=k(u,h)?0>=k(p,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=C[d+40>>2];d={Sb:C[d>>2],Rb:C[d+4>>2],kb:C[d+8>>2],eb:C[d+12>>2],Za:C[d+16>>2],Na:C[d+20>>2],lb:C[d+24>>2],mb:C[d+28>>2],Wb:C[d+32>>2],Qb:C[d+
36>>2],Tb:m?m?ma(A,m,void 0):"":""};c=c?ma(A,c,void 0):"";m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in m)c=c.replace(new RegExp(q,"g"),m[q]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return B[h.lb].substring(0,3)},"%A":function(h){return B[h.lb]},"%b":function(h){return v[h.Za].substring(0,3)},"%B":function(h){return v[h.Za]},"%C":function(h){return f((h.Na+1900)/100|0,2)},"%d":function(h){return f(h.eb,2)},"%e":function(h){return e(h.eb,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return f(h.kb,
2)},"%I":function(h){h=h.kb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.eb+Wb(Vb(h.Na+1900)?Xb:Yb,h.Za-1),3)},"%m":function(h){return f(h.Za+1,2)},"%M":function(h){return f(h.Rb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.kb&&12>h.kb?"AM":"PM"},"%S":function(h){return f(h.Sb,2)},"%t":function(){return"\t"},"%u":function(h){return h.lb||7},"%U":function(h){var p=new Date(h.Na+1900,0,1),u=0===p.getDay()?p:Zb(p,7-p.getDay());h=new Date(h.Na+1900,h.Za,h.eb);return 0>
k(u,h)?f(Math.ceil((31-u.getDate()+(Wb(Vb(h.getFullYear())?Xb:Yb,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(u,p)?"01":"00"},"%V":function(h){var p=new Date(h.Na+1901,0,4),u=l(new Date(h.Na+1900,0,4));p=l(p);var t=Zb(new Date(h.Na+1900,0,1),h.mb);return 0>k(t,u)?"53":0>=k(p,t)?"01":f(Math.ceil((u.getFullYear()<h.Na+1900?h.mb+32-u.getDate():h.mb+1-u.getDate())/7),2)},"%w":function(h){return h.lb},"%W":function(h){var p=new Date(h.Na,0,1),u=1===p.getDay()?p:Zb(p,0===p.getDay()?1:7-p.getDay()+1);h=
new Date(h.Na+1900,h.Za,h.eb);return 0>k(u,h)?f(Math.ceil((31-u.getDate()+(Wb(Vb(h.getFullYear())?Xb:Yb,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(u,p)?"01":"00"},"%y":function(h){return(h.Na+1900).toString().substring(2)},"%Y":function(h){return h.Na+1900},"%z":function(h){h=h.Qb;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Tb},"%%":function(){return"%"}};for(q in m)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),m[q](d)));q=ac(c);
if(q.length>b)return 0;E.set(q,a);return q.length-1}for(var bc=Array(256),cc=0;256>cc;++cc)bc[cc]=String.fromCharCode(cc);Ua=bc;ab=g.BindingError=$a("BindingError");bb=g.InternalError=$a("InternalError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.Ja.Ma.La,c=this.Ja.Ka,d=a.Ja.Ma.La;for(a=a.Ja.Ka;b.Qa;)c=b.fb(c),b=b.Qa;for(;d.Qa;)a=d.fb(a),d=d.Qa;return b===d&&c===a};
S.prototype.clone=function(){this.Ja.Ka||eb(this);if(this.Ja.ab)return this.Ja.count.value+=1,this;var a=ib,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ja;a=a(c.call(b,d,{Ja:{value:{count:e.count,Va:e.Va,ab:e.ab,Ka:e.Ka,Ma:e.Ma,Oa:e.Oa,Pa:e.Pa}}}));a.Ja.count.value+=1;a.Ja.Va=!1;return a};S.prototype["delete"]=function(){this.Ja.Ka||eb(this);this.Ja.Va&&!this.Ja.ab&&Q("Object already scheduled for deletion");gb(this);hb(this.Ja);this.Ja.ab||(this.Ja.Oa=void 0,this.Ja.Ka=void 0)};
S.prototype.isDeleted=function(){return!this.Ja.Ka};S.prototype.deleteLater=function(){this.Ja.Ka||eb(this);this.Ja.Va&&!this.Ja.ab&&Q("Object already scheduled for deletion");kb.push(this);1===kb.length&&jb&&jb(lb);this.Ja.Va=!0;return this};T.prototype.zb=function(a){this.vb&&(a=this.vb(a));return a};T.prototype.sb=function(a){this.Ua&&this.Ua(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=wb;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.ib?Ab(this.La.Ya,{Ma:this.Gb,Ka:c,Pa:this,Oa:a}):Ab(this.La.Ya,{Ma:this,Ka:a})}var c=this.zb(a);if(!c)return this.sb(a),null;var d=zb(this.La,c);if(void 0!==d){if(0===d.Ja.count.value)return d.Ja.Ka=c,d.Ja.Oa=a,d.clone();d=d.clone();this.sb(a);return d}d=this.La.yb(c);d=mb[d];if(!d)return b.call(this);d=this.hb?d.wb:d.pointerType;var e=xb(c,this.La,d.La);return null===e?b.call(this):this.ib?Ab(d.La.Ya,{Ma:d,Ka:e,Pa:this,Oa:a}):Ab(d.La.Ya,
{Ma:d,Ka:e})};g.getInheritedInstanceCount=function(){return Object.keys(yb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in yb)yb.hasOwnProperty(b)&&a.push(yb[b]);return a};g.flushPendingDeletes=lb;g.setDelayFunction=function(a){jb=a;kb.length&&jb&&jb(lb)};Eb=g.UnboundTypeError=$a("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<U.length;++b)void 0!==U[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<U.length;++a)if(void 0!==U[a])return U[a];return null};
function ac(a){var b=Array(oa(a)+1);na(a,b,0,b.length);return b}
var Hc={n:function(a){return Oa(a+16)+16},p:function(a){a=new L(a);var b=a.Xa();b.Bb()||(b.rb(!0),Pa--);b.jb(!1);N.push(a);b.nb();return a.Db()},da:function(){if(!N.length)return 0;var a=N[N.length-1];a.Xa().nb();return a.Wa()},L:function(a){a&&Ra(new K(a))},z:function(){V(0);var a=N.pop();Ra(a.Xa());a.pb();O=0},b:function(){var a=O;if(!a)return y=0;var b=(new K(a)).$a(),c=new L;c.cb(a);if(!b)return y=0,c.Ka|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=dc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=
d[k];if(0===l||l===b)break;if(ec(l,b,f))return b=C[f>>2],a!==b&&c.bb(b),y=l,c.Ka|0}Z(e);y=b;return c.Ka|0},k:function(){var a=O;if(!a)return y=0;var b=(new K(a)).$a(),c=new L;c.cb(a);if(!b)return y=0,c.Ka|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=dc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(ec(l,b,f))return b=C[f>>2],a!==b&&c.bb(b),y=l,c.Ka|0}Z(e);y=b;return c.Ka|0},q:function(){var a=O;if(!a)return y=0;var b=(new K(a)).$a(),c=new L;c.cb(a);if(!b)return y=
0,c.Ka|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=dc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(ec(l,b,f))return b=C[f>>2],a!==b&&c.bb(b),y=l,c.Ka|0}Z(e);y=b;return c.Ka|0},aa:function(){var a=O;if(!a)return y=0;var b=(new K(a)).$a(),c=new L;c.cb(a);if(!b)return y=0,c.Ka|0;var d=Array.prototype.slice.call(arguments),e=Y(),f=dc(4);C[f>>2]=a;for(var k=0;k<d.length;k++){var l=d[k];if(0===l||l===b)break;if(ec(l,b,f))return b=C[f>>2],a!==b&&c.bb(b),y=l,c.Ka|
0}Z(e);y=b;return c.Ka|0},o:Qa,K:function(a){a&&(new K(a)).nb()},M:Sa,ca:function(a){if(a){var b=new L;b.cb(a);a=b.Xa();N.push(b);a.jb(!0);Sa()}},s:function(a,b,c){(new K(a)).Fb(b,c);O=a;Pa++;throw a;},i:function(){return Pa},h:function(a){a=new L(a);var b=a.Wa();O||(O=b);a.pb();throw b;},ja:function(a,b,c,d,e){var f=Ta(c);b=P(b);R(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var l=E;else if(2===c)l=
sa;else if(4===c)l=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[k>>f])},Sa:null})},$:function(a,b,c,d,e,f,k,l,n,m,q,B,v){q=P(q);f=Db(e,f);l&&(l=Db(k,l));m&&(m=Db(n,m));v=Db(B,v);var h=Ya(q);ob(h,function(){Hb("Cannot construct "+q+" due to unbound types",[d])});db([a,b,c],d?[d]:[],function(p){p=p[0];if(d){var u=p.La;var t=u.Ya}else t=S.prototype;p=Za(h,function(){if(Object.getPrototypeOf(this)!==D)throw new ab("Use 'new' to construct "+q);if(void 0===F.Ta)throw new ab(q+
" has no accessible constructor");var W=F.Ta[arguments.length];if(void 0===W)throw new ab("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(F.Ta).toString()+") parameters instead!");return W.apply(this,arguments)});var D=Object.create(t,{constructor:{value:p}});p.prototype=D;var F=new pb(q,p,D,v,u,f,l,m);u=new T(q,F,!0,!1);t=new T(q+"*",F,!1,!1);var ha=new T(q+" const*",F,!1,!0);mb[a]={pointerType:t,wb:ha};Bb(h,p);return[u,t,ha]})},W:function(a,
b,c,d,e,f){0<b||z("Assertion failed: undefined");var k=Kb(b,c);e=Db(d,e);var l=[f],n=[];db([],[a],function(m){m=m[0];var q="constructor "+m.name;void 0===m.La.Ta&&(m.La.Ta=[]);if(void 0!==m.La.Ta[b-1])throw new ab("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.La.Ta[b-1]=function(){Hb("Cannot construct "+m.name+" due to unbound types",
k)};db([],k,function(B){m.La.Ta[b-1]=function(){arguments.length!==b-1&&Q(q+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var v=1;v<b;++v)l[v]=B[v].toWireType(n,arguments[v-1]);v=e.apply(null,l);Lb(n);return B[0].fromWireType(v)};return[]});return[]})},F:function(a,b,c,d,e,f,k,l){var n=Kb(c,d);b=P(b);f=Db(e,f);db([],[a],function(m){function q(){Hb("Cannot call "+B+" due to unbound types",n)}m=m[0];var B=m.name+"."+b;l&&m.La.Hb.push(b);var v=m.La.Ya,h=v[b];
void 0===h||void 0===h.Ra&&h.className!==m.name&&h.gb===c-2?(q.gb=c-2,q.className=m.name,v[b]=q):(nb(v,b,B),v[b].Ra[c-2]=q);db([],n,function(p){var u=B,t=m,D=f,F=p.length;2>F&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var ha=null!==p[1]&&null!==t,W=!1;for(t=1;t<p.length;++t)if(null!==p[t]&&void 0===p[t].Sa){W=!0;break}var Ib="void"!==p[0].name,X="",ia="";for(t=0;t<F-2;++t)X+=(0!==t?", ":"")+"arg"+t,ia+=(0!==t?", ":"")+"arg"+t+"Wired";u="return function "+
Ya(u)+"("+X+") {\nif (arguments.length !== "+(F-2)+") {\nthrowBindingError('function "+u+" called with ' + arguments.length + ' arguments, expected "+(F-2)+" args!');\n}\n";W&&(u+="var destructors = [];\n");var Jb=W?"destructors":"null";X="throwBindingError invoker fn runDestructors retType classParam".split(" ");D=[Q,D,k,Lb,p[0],p[1]];ha&&(u+="var thisWired = classParam.toWireType("+Jb+", this);\n");for(t=0;t<F-2;++t)u+="var arg"+t+"Wired = argType"+t+".toWireType("+Jb+", arg"+t+"); // "+p[t+2].name+
"\n",X.push("argType"+t),D.push(p[t+2]);ha&&(ia="thisWired"+(0<ia.length?", ":"")+ia);u+=(Ib?"var rv = ":"")+"invoker(fn"+(0<ia.length?", ":"")+ia+");\n";if(W)u+="runDestructors(destructors);\n";else for(t=ha?1:2;t<p.length;++t)F=1===t?"thisWired":"arg"+(t-2)+"Wired",null!==p[t].Sa&&(u+=F+"_dtor("+F+"); // "+p[t].name+"\n",X.push(F+"_dtor"),D.push(p[t].Sa));Ib&&(u+="var ret = retType.fromWireType(rv);\nreturn ret;\n");X.push(u+"}\n");p=Mb(X).apply(null,D);void 0===v[b].Ra?(p.gb=c-2,v[b]=p):v[b].Ra[c-
2]=p;return[]});return[]})},ia:function(a,b){b=P(b);R(a,{name:b,fromWireType:function(c){var d=U[c].value;4<c&&0===--U[c].Kb&&(U[c]=void 0,Nb.push(c));return d},toWireType:function(c,d){return ub(d)},argPackAdvance:8,readValueFromPointer:wb,Sa:null})},N:function(a,b,c){c=Ta(c);b=P(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+sb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Ob(b,
c),Sa:null})},A:function(a,b,c,d,e){function f(m){return m}b=P(b);-1===e&&(e=4294967295);var k=Ta(c);if(0===d){var l=32-8*c;f=function(m){return m<<l>>>l}}var n=b.includes("unsigned");R(a,{name:b,fromWireType:f,toWireType:function(m,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+sb(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+sb(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+
d+", "+e+"]!");return n?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Pb(b,k,0!==d),Sa:null})},x:function(a,b,c){function d(f){f>>=2;var k=G;return new e(ya,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Eb:!0})},O:function(a,b){b=P(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var l=d+
4+k;if(k==e||0==A[l]){f=f?ma(A,f,l-f):"";if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=l+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(A[d+4+k]);n=n.join("")}M(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var k=(c&&f?function(){return oa(e)}:function(){return e.length})(),l=Oa(4+
k+1);G[l>>2]=k;if(c&&f)na(e,A,l+4,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);255<n&&(M(l),Q("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=n}else for(f=0;f<k;++f)A[l+4+f]=e[f];null!==d&&d.push(M,l);return l},argPackAdvance:8,readValueFromPointer:wb,Sa:function(d){M(d)}})},H:function(a,b,c){c=P(c);if(2===b){var d=qa;var e=ta;var f=ua;var k=function(){return ra};var l=1}else 4===b&&(d=va,e=wa,f=xa,k=function(){return G},l=2);R(a,{name:c,fromWireType:function(n){for(var m=
G[n>>2],q=k(),B,v=n+4,h=0;h<=m;++h){var p=n+4+h*b;if(h==m||0==q[p>>l])v=d(v,p-v),void 0===B?B=v:(B+=String.fromCharCode(0),B+=v),v=p+b}M(n);return B},toWireType:function(n,m){"string"!==typeof m&&Q("Cannot pass non-string to C++ string type "+c);var q=f(m),B=Oa(4+q+b);G[B>>2]=q>>l;e(m,B+4,q+b);null!==n&&n.push(M,B);return B},argPackAdvance:8,readValueFromPointer:wb,Sa:function(n){M(n)}})},ka:function(a,b){b=P(b);R(a,{Vb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
P:function(){z()},Q:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Qb();else return C[fc()>>2]=28,-1;C[b>>2]=a/1E3|0;C[b+4>>2]=a%1E3*1E6|0;return 0},ba:function(a,b,c){A.copyWithin(a,b,b+c)},G:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-ya.byteLength+65535>>>16);Ba();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
fa:function(a,b){var c=0;Sb().forEach(function(d,e){var f=b+c;e=C[a+4*e>>2]=f;for(f=0;f<d.length;++f)E[e++>>0]=d.charCodeAt(f);E[e>>0]=0;c+=d.length+1});return 0},ga:function(a,b){var c=Sb();C[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});C[b>>2]=d;return 0},ha:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var k=C[b+8*f>>2],l=C[b+(8*f+4)>>2],n=0;n<l;n++){var m=A[k+n],q=Ub[a];0===m||10===m?((1===a?ea:x)(ma(q,0)),q.length=0):q.push(m)}e+=l}C[d>>2]=e;return 0},a:function(){return y},
Y:gc,u:hc,e:ic,c:jc,m:kc,r:lc,E:mc,y:nc,J:oc,D:pc,U:qc,T:rc,S:sc,V:tc,d:uc,j:vc,Z:wc,_:xc,g:yc,X:zc,f:Ac,l:Bc,t:Cc,w:Dc,B:Ec,C:Fc,R:Gc,v:function(a){return a},I:function(a){y=a},ea:function(a,b,c,d){return $b(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ja=g.asm.la;Ba();H=g.asm.ya;Da.unshift(g.asm.ma);I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Ga&&(clearInterval(Ga),Ga=null),Ha&&(e=Ha,Ha=null,e()))}function b(e){a(e.instance)}function c(e){return La().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){x("failed to asynchronously prepare wasm: "+f);z(f)})}var d={a:Hc};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return x("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return fa||"function"!==typeof WebAssembly.instantiateStreaming||Ia()||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){x("wasm streaming compile failed: "+f);x("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.ma).apply(null,arguments)};var fc=g.___errno_location=function(){return(fc=g.___errno_location=g.asm.na).apply(null,arguments)},M=g._free=function(){return(M=g._free=g.asm.oa).apply(null,arguments)},Oa=g._malloc=function(){return(Oa=g._malloc=g.asm.pa).apply(null,arguments)},Gb=g.___getTypeName=function(){return(Gb=g.___getTypeName=g.asm.qa).apply(null,arguments)};
g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.ra).apply(null,arguments)};
var Y=g.stackSave=function(){return(Y=g.stackSave=g.asm.sa).apply(null,arguments)},Z=g.stackRestore=function(){return(Z=g.stackRestore=g.asm.ta).apply(null,arguments)},dc=g.stackAlloc=function(){return(dc=g.stackAlloc=g.asm.ua).apply(null,arguments)},V=g._setThrew=function(){return(V=g._setThrew=g.asm.va).apply(null,arguments)},ec=g.___cxa_can_catch=function(){return(ec=g.___cxa_can_catch=g.asm.wa).apply(null,arguments)},Na=g.___cxa_is_pointer_type=function(){return(Na=g.___cxa_is_pointer_type=g.asm.xa).apply(null,
arguments)},Ic=g.dynCall_ji=function(){return(Ic=g.dynCall_ji=g.asm.za).apply(null,arguments)},Jc=g.dynCall_iij=function(){return(Jc=g.dynCall_iij=g.asm.Aa).apply(null,arguments)},Kc=g.dynCall_ijj=function(){return(Kc=g.dynCall_ijj=g.asm.Ba).apply(null,arguments)},Lc=g.dynCall_ijjiii=function(){return(Lc=g.dynCall_ijjiii=g.asm.Ca).apply(null,arguments)},Mc=g.dynCall_vijj=function(){return(Mc=g.dynCall_vijj=g.asm.Da).apply(null,arguments)};
g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ea).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Fa).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Ga).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ha).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Ia).apply(null,arguments)};
function ic(a,b){var c=Y();try{return H.get(a)(b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function jc(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function yc(a,b,c){var d=Y();try{H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function Ac(a,b,c,d){var e=Y();try{H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}
function vc(a,b){var c=Y();try{H.get(a)(b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}function uc(a){var b=Y();try{H.get(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;V(1,0)}}function Bc(a,b,c,d,e){var f=Y();try{H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function Cc(a,b,c,d,e,f){var k=Y();try{H.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}
function kc(a,b,c,d){var e=Y();try{return H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function lc(a,b,c,d,e){var f=Y();try{return H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function mc(a,b,c,d,e,f){var k=Y();try{return H.get(a)(b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}function nc(a,b,c,d,e,f,k){var l=Y();try{return H.get(a)(b,c,d,e,f,k)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;V(1,0)}}
function hc(a,b,c,d,e){var f=Y();try{return H.get(a)(b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function xc(a,b,c){var d=Y();try{H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function wc(a,b,c){var d=Y();try{H.get(a)(b,c)}catch(e){Z(d);if(e!==e+0&&"longjmp"!==e)throw e;V(1,0)}}function oc(a,b,c,d,e,f,k,l){var n=Y();try{return H.get(a)(b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}
function Dc(a,b,c,d,e,f,k,l){var n=Y();try{H.get(a)(b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function pc(a,b,c,d,e,f,k,l,n,m,q,B){var v=Y();try{return H.get(a)(b,c,d,e,f,k,l,n,m,q,B)}catch(h){Z(v);if(h!==h+0&&"longjmp"!==h)throw h;V(1,0)}}function Ec(a,b,c,d,e,f,k,l,n,m,q){var B=Y();try{H.get(a)(b,c,d,e,f,k,l,n,m,q)}catch(v){Z(B);if(v!==v+0&&"longjmp"!==v)throw v;V(1,0)}}
function Fc(a,b,c,d,e,f,k,l,n,m,q,B,v,h,p,u){var t=Y();try{H.get(a)(b,c,d,e,f,k,l,n,m,q,B,v,h,p,u)}catch(D){Z(t);if(D!==D+0&&"longjmp"!==D)throw D;V(1,0)}}function gc(a){var b=Y();try{return H.get(a)()}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;V(1,0)}}function zc(a,b,c,d){var e=Y();try{H.get(a)(b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function tc(a,b){var c=Y();try{return Ic(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;V(1,0)}}
function qc(a,b,c,d){var e=Y();try{return Jc(a,b,c,d)}catch(f){Z(e);if(f!==f+0&&"longjmp"!==f)throw f;V(1,0)}}function rc(a,b,c,d,e){var f=Y();try{return Kc(a,b,c,d,e)}catch(k){Z(f);if(k!==k+0&&"longjmp"!==k)throw k;V(1,0)}}function sc(a,b,c,d,e,f,k,l){var n=Y();try{return Lc(a,b,c,d,e,f,k,l)}catch(m){Z(n);if(m!==m+0&&"longjmp"!==m)throw m;V(1,0)}}function Gc(a,b,c,d,e,f){var k=Y();try{Mc(a,b,c,d,e,f)}catch(l){Z(k);if(l!==l+0&&"longjmp"!==l)throw l;V(1,0)}}var Nc;
Ha=function Oc(){Nc||Pc();Nc||(Ha=Oc)};
function Pc(){function a(){if(!Nc&&(Nc=!0,g.calledRun=!0,!ka)){Ma(Da);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ea.unshift(b)}Ma(Ea)}}if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Fa();Ma(Ca);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=Pc;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Pc();


  return Tiro.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = Tiro;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return Tiro; });
else if (typeof exports === 'object')
  exports["Tiro"] = Tiro;
