name: Deploy

on:
    push:
        branches:
        - "master"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "yarn"

            # Setup nextjs caching: https://nextjs.org/docs/messages/no-cache
            - uses: actions/cache@v2
              with:
                path: ${{ github.workspace }}/packages/website/.next/cache
                # Generate a new cache whenever packages or source files change.
                key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                # If source files changed but packages didn't, rebuild from a prior cache.
                restore-keys: |
                    ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

            - name: "Setup git"
              shell: bash
              run: |
                git config user.name github-actions
                git config user.email github-actions@github.com

            - name: Install dependencies
              shell: bash
              run: yarn install

            - name: Run checks
              shell: bash
              run: yarn run lint

            - name: Deploy
              shell: bash
              run: |
                  git fetch --no-tags --prune --progress --depth=1 origin site
                  yarn run init-site
                  yarn run deploy
